/**
 * Category Averages — computed from fund-cache.json at build time
 * 
 * When a fund doesn't have data for a specific timeframe (e.g., new fund with no 5Y history),
 * we fall back to the average return of its SEBI category instead of a hardcoded number.
 * 
 * This file is auto-generated by computeCategoryAverages() from the cache data.
 * It's also importable as a static module for instant access.
 */

import fundCacheData from '@/data/fund-cache.json';

interface CategoryAverage {
  '1y': number | null;
  '3y': number | null;
  '5y': number | null;
  '10y': number | null;
}

// Broader category mapping: normalize SEBI sub-categories into investment-relevant groups
// This handles the fact that AMFI categories are very granular
const CATEGORY_GROUPS: Record<string, string> = {
  // Equity
  'Large Cap Fund': 'equity-largecap',
  'Equity Scheme - Large Cap Fund': 'equity-largecap',
  'Mid Cap Fund': 'equity-midcap',
  'Equity Scheme - Mid Cap Fund': 'equity-midcap',
  'Small Cap Fund': 'equity-smallcap',
  'Equity Scheme - Small Cap Fund': 'equity-smallcap',
  'Flexi Cap Fund': 'equity-flexicap',
  'Equity Scheme - Flexi Cap Fund': 'equity-flexicap',
  'Multi Cap Fund': 'equity-multicap',
  'Large & Mid Cap fund': 'equity-largemid',
  'Equity Scheme - Large & Mid Cap Fund': 'equity-largemid',
  'ELSS': 'equity-elss',
  'Equity Scheme - ELSS': 'equity-elss',
  'Value Fund': 'equity-value',
  'Contra Fund': 'equity-value',
  'Focused Fund': 'equity-focused',
  'Dividend Yield Fund': 'equity-dividend',
  'Sectoral/Thematic': 'equity-sectoral',
  'Equity Scheme - Sectoral/ Thematic': 'equity-sectoral',
  'Equity - ESG Fund': 'equity-sectoral',
  'Index Funds': 'index',
  'Index Fund': 'index',
  'Other Scheme - Index Funds': 'index',
  'Index Funds - Fixed Income': 'debt-index',

  // Debt
  'Short Duration Fund': 'debt-short',
  'Debt Scheme - Short Duration Fund': 'debt-short',
  'Corporate Bond Fund': 'debt-corporate',
  'Debt Scheme - Corporate Bond Fund': 'debt-corporate',
  'Banking and PSU Fund': 'debt-banking',
  'Debt Scheme - Banking and PSU Fund': 'debt-banking',
  'Gilt Fund': 'debt-gilt',
  'Debt Scheme - Gilt Fund': 'debt-gilt',
  'Gilt Fund with 10 year constant duration': 'debt-gilt',
  'Debt Scheme - Gilt Fund with 10 year constant duration': 'debt-gilt',
  'Dynamic Bond': 'debt-dynamic',
  'Debt Scheme - Dynamic Bond': 'debt-dynamic',
  'Low Duration Fund': 'debt-low',
  'Debt Scheme - Low Duration Fund': 'debt-low',
  'Medium Duration Fund': 'debt-medium',
  'Debt Scheme - Medium Duration Fund': 'debt-medium',
  'Medium to Long Duration Fund': 'debt-medium',
  'Debt Scheme - Medium to Long Duration Fund': 'debt-medium',
  'Long Duration Fund': 'debt-long',
  'Debt Scheme - Long Duration Fund': 'debt-long',
  'Credit Risk Fund': 'debt-credit',
  'Debt Scheme - Credit Risk Fund': 'debt-credit',
  'Liquid Fund': 'debt-liquid',
  'Debt Scheme - Liquid Fund': 'debt-liquid',
  'Ultra Short Duration Fund': 'debt-ultrashort',
  'Debt Scheme - Ultra Short Duration Fund': 'debt-ultrashort',
  'Money Market Fund': 'debt-money',
  'Debt Scheme - Money Market Fund': 'debt-money',
  'Overnight Fund': 'debt-overnight',
  'Debt Scheme - Overnight Fund': 'debt-overnight',
  'Floater Fund': 'debt-floater',
  'Debt Scheme - Floater Fund': 'debt-floater',
  'Income': 'debt-short',

  // Hybrid
  'Aggressive Hybrid Fund': 'hybrid-aggressive',
  'Hybrid Scheme - Aggressive Hybrid Fund': 'hybrid-aggressive',
  'Dynamic Asset Allocation or Balanced Advantage': 'hybrid-baf',
  'Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage': 'hybrid-baf',
  'Conservative Hybrid Fund': 'hybrid-conservative',
  'Hybrid Scheme - Conservative Hybrid Fund': 'hybrid-conservative',
  'Equity Savings': 'hybrid-savings',
  'Hybrid Scheme - Equity Savings': 'hybrid-savings',
  'Multi Asset Allocation': 'hybrid-multiasset',
  'Hybrid Scheme - Multi Asset Allocation': 'hybrid-multiasset',
  'Arbitrage Fund': 'hybrid-arbitrage',
  'Hybrid Scheme - Arbitrage Fund': 'hybrid-arbitrage',
  'Balanced Hybrid Fund': 'hybrid-baf',
  'Hybrid Scheme - Balanced Hybrid Fund': 'hybrid-baf',

  // Others
  'Fund of Funds': 'fof',
  'Other Scheme - FoF Domestic': 'fof',
  'Other Scheme - FoF Overseas': 'international',
  'Retirement Fund': 'hybrid-aggressive',
  'Solution Oriented Scheme - Retirement Fund': 'hybrid-aggressive',
  'Childrens Fund': 'hybrid-aggressive',
  'Solution Oriented Scheme - Children\'s Fund': 'hybrid-aggressive',
  'Gold': 'gold',
};

function computeAverages(): Record<string, CategoryAverage> {
  const cache = fundCacheData as { funds: Record<string, { category: string; cagr: Record<string, number | null> }> };
  const groups: Record<string, { '1y': number[]; '3y': number[]; '5y': number[]; '10y': number[] }> = {};

  for (const fund of Object.values(cache.funds)) {
    const group = CATEGORY_GROUPS[fund.category] || 'unknown';
    if (!groups[group]) groups[group] = { '1y': [], '3y': [], '5y': [], '10y': [] };

    if (fund.cagr['1y'] != null) groups[group]['1y'].push(fund.cagr['1y']);
    if (fund.cagr['3y'] != null) groups[group]['3y'].push(fund.cagr['3y']);
    if (fund.cagr['5y'] != null) groups[group]['5y'].push(fund.cagr['5y']);
    if (fund.cagr['10y'] != null) groups[group]['10y'].push(fund.cagr['10y']);
  }

  const result: Record<string, CategoryAverage> = {};
  for (const [group, data] of Object.entries(groups)) {
    const avg = (arr: number[]) => arr.length >= 2 ? Math.round((arr.reduce((a, b) => a + b, 0) / arr.length) * 10) / 10 : null;
    result[group] = { '1y': avg(data['1y']), '3y': avg(data['3y']), '5y': avg(data['5y']), '10y': avg(data['10y']) };
  }

  return result;
}

// Computed once at module load (build time for SSR, once on client)
const CATEGORY_AVERAGES = computeAverages();

/**
 * Get the category average return for a given fund category and timeframe.
 * Used as fallback when a specific fund doesn't have data for that timeframe.
 */
export function getCategoryAverage(category: string, timeframe: '1y' | '3y' | '5y' | '10y'): number | null {
  const group = CATEGORY_GROUPS[category] || 'unknown';
  return CATEGORY_AVERAGES[group]?.[timeframe] ?? null;
}

/**
 * Get the category group name for a fund category.
 */
export function getCategoryGroup(category: string): string {
  return CATEGORY_GROUPS[category] || 'unknown';
}

/**
 * Get all computed category averages (for debugging/display).
 */
export function getAllCategoryAverages(): Record<string, CategoryAverage> {
  return CATEGORY_AVERAGES;
}
